
# w. stabilizer
target: 'door'
date: 'Feb17'
data_dir: 'H:\phone_Lidar\data\prelim\LabFeb17\door\data'
data_type: 'img'
img_extension: 'jpeg'
checkpoint_file: 'H:\phone_Lidar\data\prelim\LabFeb17\door\door-2Dkps.pkl'
cam_yml: 'H:\phone_Lidar\data\prelim\Feb14\wen14_portrait.yml'

# w/o stabilizer
#target: MEPbox
#date: Oct31
#data_dir: H:\phone_Lidar\data\prelim\oct31\2022-10-31 16_57_40\data
#checkpoint_file: H:\phone_Lidar\data\prelim\oct31\scene-1-2Dkps.pkl
#cam_yml: H:\phone_Lidar\data\prelim\oct11\Hongxiao_portrait.yml
#data_type: img
#img_extension: jpeg


kp_nos: 8
kp_names: ['door_topright','door_topleft','door_bottomright','door_bottomleft',
           'frame_topright','frame_topleft','frame_bottomright','frame_bottomleft']
dist_gt: [1009,1009,2112,2112,
          1116,1100,2186,2186]
dist_sequences: [[0, 1], [3, 2], [1, 3], [2, 0],
                 [4, 5], [7, 6], [5, 7], [6, 4]]





