target: 'Mair'
date: 'Feb12'
data_dir: 'Y:\phone_Lidar\data\prelim\M-airFeb12\Try2.5\data'
data_type: 'img'
img_extension: 'jpeg'
checkpoint_file: 'Y:\phone_Lidar\data\prelim\M-airFeb12\Try2.5\M-air-2Dkps.pkl'
cam_yml: 'Y:\phone_Lidar\data\prelim\Feb14\wen14_portrait.yml'

kp_nos: 8
kp_names: ['TopRightFront,BotRightFront,TopRightBack,BotRightBack,TopLeftFront,BotLeftFront,TopLeftBack,BotLeftBack']
dist_gt: [3158, 3144, 3177, 3177, 5731, 5711, 11140, 11123]
dist_sequences: [[0,1],[2,3],[4,5],[6,7],[1,3],[5,7],[1,5],[3,7]]


